# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin = Usuario.create(email: "admin@gmail.com", password: 123456, password_confirmation: 123456, primerNombre: "Cristian", segundoNombre: "Andres", primerApellido: "Julio")
usuario = Usuario.create(email: "usuario@gmail.com", password: 123456, password_confirmation: 123456, primerNombre: "Andrea", segundoNombre: "Camila", primerApellido: "Davila")

a1 = Agente.create(primerNombre: "Jesus", segundoNombre: "Camilo", primerApellido: "Torres", nombreUds: "Niño jesus", modalidad: "Tradicional", correo: "jesus@gmail.com", cedula: 1001779301)
a2 =Agente.create(primerNombre: "Maria", segundoNombre: "Agustina", primerApellido: "Vázquez", nombreUds: "Mis pequeños", modalidad: "Familiar", correo: "maria@gmail.com", cedula: 1001779302)
a3 = Agente.create(primerNombre: "Carlos", segundoNombre: "Camilo", primerApellido: "Gil", nombreUds: "Angelitos", modalidad: "Tradicional", correo: "carlos@gmail.com", cedua: 1001779303)
a4 = Agente.create(primerNombre: "Diana", segundoNombre: "Isidora", primerApellido: "Llorente", nombreUds: "Pequeños", modalidad: "Familiar", correo: "diana@gmail.com", cedula: 1001779304)
a5 = Agente.create(primerNombre: "Mario", segundoNombre: "Camilo", primerApellido: "Menéndez", nombreUds: "Traviesos", modalidad: "Tradicional", correo: "mario@gmail.com", cedula: 1001779305)
a6 = Agente.create(primerNombre: "Hector", segundoNombre: "Camilo", primerApellido: "Salmerón", nombreUds: "Laureles", modalidad: "Propia", correo: "hector@gmail.com", cedula: 1001779306)
a7 = Agente.create(primerNombre: "Jose", segundoNombre: "Camilo", primerApellido: "Perón", nombreUds: "Jardines de la paz", modalidad: "Tradicional", correo: "jose@gmail.com", cedula: 1001779307)
a8 = Agente.create(primerNombre: "Isabel", segundoNombre: "Emma", primerApellido: "Pérez", nombreUds: "Pequeños gigantes", modalidad: "Propia", correo: "isabel@gmail.com", cedula: 1001779308)
a9 = Agente.create(primerNombre: "Antonio", segundoNombre: "Camilo", primerApellido: "Montalbán", nombreUds: "Chiquitines", modalidad: "Institucional", correo: "antonio@gmail.com", cedula: 1001779309)
a10 = Agente.create(primerNombre: "Rosa", segundoNombre: "Renata", primerApellido: "Valverde", nombreUds: "Jardines las flores", modalidad: "Tradicional", correo: "rosa@gmail.com", cedula: 1001779300)
a11 = Agente.create(primerNombre: "Pedro", segundoNombre: "Camilo", primerApellido: "Gómez", nombreUds: "Nombre", modalidad: "Tradicional", correo: "pedro@gmail.com", cedula: 1001779310)
a12 = Agente.create(primerNombre: "Sagrario", segundoNombre: "Catalina", primerApellido: "Alonso", nombreUds: "Nombre", modalidad: "Tradicional", correo: "sagrario@gmail.com", cedula: 1001779311)
a13 = Agente.create(primerNombre: "Jaime", segundoNombre: "Camilo", primerApellido: "Ortiz", nombreUds: "Nombre", modalidad: "Tradicional", correo: "jaime@gmail.com", cedula: 1001779312)
a14 = Agente.create(primerNombre: "Dolores", segundoNombre: "Antonella", primerApellido: "Embuena", nombreUds: "Nombre", modalidad: "Propia", correo: "dolores@gmail.com", cedula: 1001779313)
a15 = Agente.create(primerNombre: "Azucena", segundoNombre: "Amanda", primerApellido: "Aretio", nombreUds: "Nombre", modalidad: "Familiar", correo: "azucena@gmail.com", cedula: 1001779314)
a16 = Agente.create(primerNombre: "Felis", segundoNombre: "Camilo", primerApellido: "Revuelta", nombreUds: "Nombre", modalidad: "Tradicional", correo: "felis@gmail.com", cedula: 100177915)
a17 = Agente.create(primerNombre: "Yolanda", segundoNombre: "Maite", primerApellido: "Pardo", nombreUds: "Nombre", modalidad: "Familiar", correo: "yolanda@gmail.com", cedula: 1001779316)
a18 = Agente.create(primerNombre: "Gemma", segundoNombre: "Florencia", primerApellido: "Bazán", nombreUds: "Nombre", modalidad: "Institucional", correo: "gemma@gmail.com", cedula: 1001779317)
a19 = Agente.create(primerNombre: "Eduardo", segundoNombre: "Camilo", primerApellido: "Langa", nombreUds: "Nombre", modalidad: "Tradicional", correo: "eduardo@gmail.com", cedula: 1001779318)
a20 = Agente.create(primerNombre: "Oscar", segundoNombre: "Camilo", primerApellido: "Martínez", nombreUds: "Nombre", modalidad: "Tradicional", correo: "oscar@gmail.com", cedula: 1001779319)
a21 = Agente.create(primerNombre: "Rodolfo", segundoNombre: "Camilo", primerApellido: "Gallardo", nombreUds: "Nombre", modalidad: "Propia", correo: "rodolfo@gmail.com", cedula: 1001779320)
a22 = Agente.create(primerNombre: "Tomás", segundoNombre: "Camilo", primerApellido: "Estriado", nombreUds: "Nombre", modalidad: "Tradicional", correo: "tomas@gmail.com", cedula: 1001779321)
a23 = Agente.create(primerNombre: "Aurora", segundoNombre: "Trinidad", primerApellido: "Cifuentes", nombreUds: "Nombre", modalidad: "Propia", correo: "aurora@gmail.com", cedula: 1001779322)
a24 = Agente.create(primerNombre: "Mateo", segundoNombre: "Camilo", primerApellido: "Alesón", nombreUds: "Nombre", modalidad: "Tradicional", correo: "mateo@gmail.com", cedula: 1001779323)
a25 = Agente.create(primerNombre: "Ignacio", segundoNombre: "Camilo", primerApellido: "Delgado", nombreUds: "Nombre", modalidad: "Tradicional", correo: "ignacio@gmail.com", cedula: 1001779324)
a26 = Agente.create(primerNombre: "Sofía", segundoNombre: "Nicole", primerApellido: "Plaza", nombreUds: "Nombre", modalidad: "Propia", correo: "sofia@gmail.com", cedula: 1001779325)
a27 = Agente.create(primerNombre: "Emilia", segundoNombre: "Paola", primerApellido: "Marino", nombreUds: "Nombre", modalidad: "Propia", correo: "emilia@gmail.com", cedula: 1001779326)
a28 = Agente.create(primerNombre: "Josefa", segundoNombre: "Fernanda", primerApellido: "Pardo", nombreUds: "Nombre", modalidad: "Tradicional", correo: "josefa@gmail.com", cedula: 1001779327)
a29 = Agente.create(primerNombre: "Julieta", segundoNombre: "Ana", primerApellido: "Ortiz", nombreUds: "Nombre", modalidad: "Institucional", correo: "julieta@gmail.com", cedula: 1001779328)
a30 = Agente.create(primerNombre: "Mia", segundoNombre: "Rubí", primerApellido: "Langa", nombreUds: "Nombre", modalidad: "Tradicional", correo: "mia@gmail.com", cedula: 1001779329)
