# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin = Usuario.create(email: "admin@gmail.com", password: 123456, password_confirmation: 123456, primerNombre: "Cristian", segundoNombre: "Andres", primerApellido: "Julio")
usuario = Usuario.create(email: "usuario@gmail.com", password: 123456, password_confirmation: 123456, primerNombre: "Andrea", segundoNombre: "Camila", primerApellido: "Davila")

a1 = Agente.create(primerNombre: "Jesus", segundoNombre: "Camilo", primerApellido: "Torres", nombreUds: "Nombre", modalidad: "Tradicional", correo: "jesus@gmail.com", cedula: 3)
a2 =Agente.create(primerNombre: "Maria", segundoNombre: "Agustina", primerApellido: "Vázquez", nombreUds: "Nombre", modalidad: "Familiar", correo: "maria@gmail.com", cedula: 4)
a3 = Agente.create(primerNombre: "Carlos", segundoNombre: "Camilo", primerApellido: "Gil", nombreUds: "Nombre", modalidad: "Tradicional", correo: "carlos@gmail.com", cedula: 5)
a4 = Agente.create(primerNombre: "Diana", segundoNombre: "Isidora", primerApellido: "Llorente", nombreUds: "Nombre", modalidad: "Familiar", correo: "diana@gmail.com", cedula: 6)
a5 = Agente.create(primerNombre: "Mario", segundoNombre: "Camilo", primerApellido: "Menéndez", nombreUds: "Nombre", modalidad: "Tradicional", correo: "mario@gmail.com", cedula: 7)
a6 = Agente.create(primerNombre: "Hector", segundoNombre: "Camilo", primerApellido: "Salmerón", nombreUds: "Nombre", modalidad: "Propia", correo: "hector@gmail.com", cedula: 8)
a7 = Agente.create(primerNombre: "Jose", segundoNombre: "Camilo", primerApellido: "Perón", nombreUds: "Nombre", modalidad: "Tradicional", correo: "jose@gmail.com", cedula: 9)
a8 = Agente.create(primerNombre: "Isabel", segundoNombre: "Emma", primerApellido: "Pérez", nombreUds: "Nombre", modalidad: "Propia", correo: "isabel@gmail.com", cedula: 10)
a9 = Agente.create(primerNombre: "Antonio", segundoNombre: "Camilo", primerApellido: "Montalbán", nombreUds: "Nombre", modalidad: "Institucional", correo: "antonio@gmail.com", cedula: 11)
a10 = Agente.create(primerNombre: "Rosa", segundoNombre: "Renata", primerApellido: "Valverde", nombreUds: "Nombre", modalidad: "Tradicional", correo: "rosa@gmail.com", cedula: 12)
a11 = Agente.create(primerNombre: "Pedro", segundoNombre: "Camilo", primerApellido: "Gómez", nombreUds: "Nombre", modalidad: "Tradicional", correo: "pedro@gmail.com", cedula: 13)
a12 = Agente.create(primerNombre: "Sagrario", segundoNombre: "Catalina", primerApellido: "Alonso", nombreUds: "Nombre", modalidad: "Tradicional", correo: "sagrario@gmail.com", cedula: 14)
a13 = Agente.create(primerNombre: "Jaime", segundoNombre: "Camilo", primerApellido: "Ortiz", nombreUds: "Nombre", modalidad: "Tradicional", correo: "jaime@gmail.com", cedula: 15)
a14 = Agente.create(primerNombre: "Dolores", segundoNombre: "Antonella", primerApellido: "Embuena", nombreUds: "Nombre", modalidad: "Propia", correo: "dolores@gmail.com", cedula: 16)
a15 = Agente.create(primerNombre: "Azucena", segundoNombre: "Amanda", primerApellido: "Aretio", nombreUds: "Nombre", modalidad: "Familiar", correo: "azucena@gmail.com", cedula: 17)
a16 = Agente.create(primerNombre: "Felis", segundoNombre: "Camilo", primerApellido: "Revuelta", nombreUds: "Nombre", modalidad: "Tradicional", correo: "felis@gmail.com", cedula: 18)
a17 = Agente.create(primerNombre: "Yolanda", segundoNombre: "Maite", primerApellido: "Pardo", nombreUds: "Nombre", modalidad: "Familiar", correo: "yolanda@gmail.com", cedula: 19)
a18 = Agente.create(primerNombre: "Gemma", segundoNombre: "Florencia", primerApellido: "Bazán", nombreUds: "Nombre", modalidad: "Institucional", correo: "gemma@gmail.com", cedula: 20)
a19 = Agente.create(primerNombre: "Eduardo", segundoNombre: "Camilo", primerApellido: "Langa", nombreUds: "Nombre", modalidad: "Tradicional", correo: "eduardo@gmail.com", cedula: 21)
a20 = Agente.create(primerNombre: "Oscar", segundoNombre: "Camilo", primerApellido: "Martínez", nombreUds: "Nombre", modalidad: "Tradicional", correo: "oscar@gmail.com", cedula: 22)
a21 = Agente.create(primerNombre: "Rodolfo", segundoNombre: "Camilo", primerApellido: "Gallardo", nombreUds: "Nombre", modalidad: "Propia", correo: "rodolfo@gmail.com", cedula: 23)
a22 = Agente.create(primerNombre: "Tomás", segundoNombre: "Camilo", primerApellido: "Estriado", nombreUds: "Nombre", modalidad: "Tradicional", correo: "tomas@gmail.com", cedula: 24)
a23 = Agente.create(primerNombre: "Aurora", segundoNombre: "Trinidad", primerApellido: "Cifuentes", nombreUds: "Nombre", modalidad: "Propia", correo: "aurora@gmail.com", cedula: 25)
a24 = Agente.create(primerNombre: "Mateo", segundoNombre: "Camilo", primerApellido: "Alesón", nombreUds: "Nombre", modalidad: "Tradicional", correo: "mateo@gmail.com", cedula: 26)
a25 = Agente.create(primerNombre: "Ignacio", segundoNombre: "Camilo", primerApellido: "Delgado", nombreUds: "Nombre", modalidad: "Tradicional", correo: "ignacio@gmail.com", cedula: 27)
a26 = Agente.create(primerNombre: "Sofía", segundoNombre: "Nicole", primerApellido: "Plaza", nombreUds: "Nombre", modalidad: "Propia", correo: "sofia@gmail.com", cedula: 28)
a27 = Agente.create(primerNombre: "Emilia", segundoNombre: "Paola", primerApellido: "Marino", nombreUds: "Nombre", modalidad: "Propia", correo: "emilia@gmail.com", cedula: 29)
a28 = Agente.create(primerNombre: "Josefa", segundoNombre: "Fernanda", primerApellido: "Pardo", nombreUds: "Nombre", modalidad: "Tradicional", correo: "josefa@gmail.com", cedula: 30)
a29 = Agente.create(primerNombre: "Julieta", segundoNombre: "Ana", primerApellido: "Ortiz", nombreUds: "Nombre", modalidad: "Institucional", correo: "julieta@gmail.com", cedula: 31)
a30 = Agente.create(primerNombre: "Mia", segundoNombre: "Rubí", primerApellido: "Langa", nombreUds: "Nombre", modalidad: "Tradicional", correo: "mia@gmail.com", cedula: 32)
